export const ListOfThemes = {
  Light: {
    primary: "#003366",
    background: "#feffff",
    text: "#2b2c34",
    windowBarBackground: "#cbe6ef",
    windowBarText: "black",
    WindowBarIcon: "black",
    SideBarBackground: "#71b1c5",
    SideBarText: "black",
    SideBarIconText: "white",
    SideBarIconActiveBackground: "#003366",
    SideBarIconInActiveBackground: "#c7daed",
    MailCardBackground: "#cbe6ef",
    MailCardUserIconBackground: "#003366",
    MailCardUserIconText: "white",
    MailCardTime: "black",
    MailCardSenderText: "black",
    MailCardStarredIcon: "red",
    MailCardMessageTruncated: "black",
    MailCardReadButtonBackground: "#003366",
    MailCardReadButtonText: "white",
    MailCardUnreadIcon: "black",
    MailCardSenderName: "red",
    RightIntroName: "#003366",
    RightIntroDescription: "black",
    StatCardBackground: "#cbe6ef",
    StatCardText: "black",
    BannerCardBackground: "#cbe6ef",
    BannerCardText: "black",
    BannerCardButtonBackground: "#003366",
    BannerCardButtonText: "white",
    BannerCardTitle: "#003366",
    SupportCardBackground: "#71b1c5",
    SupportCardText: "black",
    SupportCardButtonBackground: "#003366",
    SupportCardButtonText: "white",
    SupportCardTitle: "#003366",
    searchBackground: "#ededed",
    searchText: "black",
    SearchIcons: "black",
    UserEmailText: "black",
    LoadingText: "black",
    LoadingBackground: "#ededed",
    LoadingIcon: "#003366",
    DisplayMailTopIconBackground: "#003366",
    DisplayMailTopIcon: "white",
    DisplayMailUserIconBackground: "#003366",
    DisplayMailUserIcon: "white",
    DisplayMailToolTip: "#003366",
    DisplayMailSenderIcon: "black",
    PaletteName: "Light",
    isDarkScheme: false,
  },
  // Dark: {
  //   primary: "#003366",
  //   background: "#000000",
  //   text: "white",
  //   windowBarBackground: "#000039",
  //   windowBarText: "white",
  //   SideBarBackground: "#1b1b1b",
  //   SideBarText: "white",
  //   IconActiveBackground: "#ededed",
  //   IconInActiveBackground: "#333333",
  //   CardBackground: "#0d0d0d",
  //   PaletteName: "Dark",
  //   isDarkScheme: true,
  // },
};
