export const UserTypes = {
	SET_USER: "SET_USER",
	SET_TOKEN: "SET_TOKEN",
	SET_UID: "SET_UID",
	SET_AUTHENTICATED: "SET_AUTHENTICATED"
};

export const LoadingTypes = {
	SET_LOADING: "SET_LOADING",
};

export const ThemeTypes = {
	SET_THEME: "SET_THEME",
};

export const settingsType = {
	general: {
		THEME_PREFERENCE: "THEME_PREFERENCE",
	},
	privacy: {},
};

export const MailType = {
	SET_ALL_MAILS: "SET_ALL_MAILS",
	SET_ENVELOPE: "SET_ENVELOPE",
	SET_DRAFT_MAILS: "SET_DRAFT_MAILS",
	SET_SENT_MAILS: "SET_SENT_MAILS",
	SET_TRASH_MAILS: 'SET_TRASH_MAILS',
	SET_SPAM_MAILS: "SET_SPAM_MAILS",
	SET_IMPORTANT_MAILS: "SET_IMPORTANT_MAILS",
	SET_STARRED_MAILS: "SET_STARRED_MAILS",
}

export const APP_IDENTIFIER = {
	SET_IS_OPENING_FIRST: "SET_IS_OPENING_FIRST"
}